spring:
  mvc:
    view:
      prefix: /
      suffix: .html
  datasource:
      driver-class-name: com.mysql.jdbc.Driver   #mysql的驱动
      url: jdbc:mysql://127.0.0.1:3306/wxtrick
      username: root
      password: root
  jpa:
    hibernate:
      ddl-auto: update         #【重点！以后选中不同的功能项时修改此处配置即可】这只是对于表的操作，具体数据的操作还需看Controller
                  #create是每次启动都将重新创建一个只有格式没有内容的空表,update则不会
                  #create-drop表示应用停下来时会自动把表删掉
                  #none表示默认什么都不做
                  #validate会验证表的属性是否与期望的一致，若不一致将报错
      show-sql: true

qiniu:
  AK: y-wrlAVBlsnIYFyP8CVoMB28VWW0onb-OtTrr_yW
  SK: mjaX8bxphou9iMP8spUl9JgxYmiwIZbdb9i96a5d
  spacename: wxtrick
  openUrl: http://p7xnxhjxx.bkt.clouddn.com


server:
  #context-path: /recommends
  port: 8080
  servlet:
    context-path: /recommends